android.useAndroidX=true
android.enableJetifier=true

# Reducimos el heap de Gradle a 1.5GB para dejar aire al sistema
org.gradle.jvmargs=-Xmx1536m -XX:MaxMetaspaceSize=512m -Dfile.encoding=UTF-8 -XX:+HeapDumpOnOutOfMemoryError

# Optimizamos el demonio de Kotlin para que no use un proceso separado tan grande
kotlin.daemon.jvmargs=-Xmx1024m
kotlin.code.style=official

# Forzamos a que Kotlin use menos memoria en la estrategia de compilación
kotlin.incremental.useClasspathSnapshot=false
